### PR TITLE
Add workers

### PR DESCRIPTION
**Pull request by asavershin**

### CODE REVIEW

**Comment by asavershin** [comment]
|Overall Project|81.89% **`-5.25%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|67.28%|:green_apple:|
<br>

|Module|Coverage||
|:-|:-|:-:|
|api|85.11%|:green_apple:|
|worker|61.48% **`-38.52%`**|:green_apple:|

<details>
<summary>Files</summary>

|Module|File|Coverage||
|:-|:-|:-|:-:|
|api|[MinioServiceIml.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fstorage%2FMinioServiceIml.java)|77.87%|:green_apple:|
||[Filter.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Ffilter%2FFilter.java)|60%|:green_apple:|
|worker|[BlackWhiteWorker.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FBlackWhiteWorker.java)|88.28% **`-11.72%`**|:green_apple:|
||[RotateImage.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FRotateImage.java)|83.96% **`-16.04%`**|:green_apple:|
||[DoneProducer.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fout%2Fproducers%2FDoneProducer.java)|42.86% **`-57.14%`**|:x:|
||[WipProducer.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fout%2Fproducers%2FWipProducer.java)|42.86% **`-57.14%`**|:x:|
||[Consumer.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fin%2FConsumer.java)|30.16% **`-69.84%`**|:x:|
||[WorkerManagerImpl.java](https://github.com/asavershin/Images/blob/24cc8efac016a00a496cfd90d6e658c23ef69bca/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FWorkerManagerImpl.java)|11.84% **`-88.16%`**|:x:|

</details>

**Comment by asavershin** [comment]
c0d8b3f6-7b1f-4f67-9abc-319b3230368c
Example

**Comment by asavershin** [comment]
success
Example

**Review by MaximKozlyuk — APPROVED** [review]

**Comment by asavershin** [comment]
|Overall Project|82.03% **`-6.68%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|74.62%|:green_apple:|
<br>

|Module|Coverage||
|:-|:-|:-:|
|api|85.14%|:green_apple:|
|worker|72.2% **`-27.8%`**|:green_apple:|

<details>
<summary>Files</summary>

|Module|File|Coverage||
|:-|:-|:-|:-:|
|api|[MinioServiceIml.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fstorage%2FMinioServiceIml.java)|77.87%|:green_apple:|
||[Filter.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Ffilter%2FFilter.java)|67.74%|:green_apple:|
|worker|[BlackWhiteWorker.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FBlackWhiteWorker.java)|88.28% **`-11.72%`**|:green_apple:|
||[RotateImage.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FRotateImage.java)|83.96% **`-16.04%`**|:green_apple:|
||[ImaggaWorker.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FImaggaWorker.java)|82.86% **`-17.14%`**|:green_apple:|
||[DoneProducer.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fout%2Fproducers%2FDoneProducer.java)|42.86% **`-57.14%`**|:x:|
||[WipProducer.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fout%2Fproducers%2FWipProducer.java)|42.86% **`-57.14%`**|:x:|
||[Consumer.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fin%2FConsumer.java)|30.16% **`-69.84%`**|:x:|
||[WorkerManagerImpl.java](https://github.com/asavershin/Images/blob/0769cb9b3833e223207564a232c53fc702ddb9f6/worker%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fworker%2Fservices%2FWorkerManagerImpl.java)|11.84% **`-88.16%`**|:x:|

</details>

**Pull request merged**
