### PR TITLE
Add api

### PR DESCRIPTION
**Pull request by asavershin**

### CODE REVIEW

**Comment by asavershin** [comment]
PostgreSQL выбрана для хранения метаинформации, так как +- известна структура этой самой метаинформации. К тому же хранение пользователей в SQL бд, а картинки, например, в Mongo создаст дополнительную кодовую нагрузку на уровне application по контролю консистентности данных

**Comment by MaximKozlyuk** [comment]
Работа хорошая
Ты видимо эту структуру папок с in/out взял из гексоганальной архитектуры? Ну интересно чем конкретно вдохновлялся.

Сложно это критиковать если честно, что-то аналогичное сейчас в команде в свежих микросервисах используем. Мы даже не стали пока выделять отдельные аннотации типа твоих `Command` хотя возможно стоит:)
Нравится что логика по небольшим классам упакована под четким интерфейсом.

**Review by MaximKozlyuk — APPROVED** [review]

**Comment by asavershin** [comment]
По большей части вдохновлялся из Эванса DDD и Вона Вернона. Иерархию уже сам накидывал примерно рассуждая, как бы это лучше было с точки зрения того же DDD, по мелочёвки ещё смотрел видосы ребят на шарпах. Но тут всё очень индивидуально, конкретно я так захотел сделать. А так, да, в основном глаз пал на гексоганалку в качестве обёртки для DDD.

**Comment by asavershin** [comment]
|Overall Project|81.5% **`-18.5%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|81.5%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[AuthenticatedUserRepositoryImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fpersistence%2FAuthenticatedUserRepositoryImpl.java)|100%|:green_apple:|
|[UserRepositoryImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fpersistence%2FUserRepositoryImpl.java)|100%|:green_apple:|
|[ImageRepositoryImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fpersistence%2FImageRepositoryImpl.java)|100%|:green_apple:|
|[PartOfResources.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2FPartOfResources.java)|100%|:green_apple:|
|[ResourceOwnershipException.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2FResourceOwnershipException.java)|100%|:green_apple:|
|[IsEntityFound.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2FIsEntityFound.java)|100%|:green_apple:|
|[DeleteImageOfUserImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2Fimpl%2FDeleteImageOfUserImpl.java)|100%|:green_apple:|
|[GetImageOfUserImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2Fimpl%2FGetImageOfUserImpl.java)|100%|:green_apple:|
|[GetPartImagesOfUserImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2Fimpl%2FGetPartImagesOfUserImpl.java)|100%|:green_apple:|
|[StoreImageOfUserImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2Fimpl%2FStoreImageOfUserImpl.java)|100%|:green_apple:|
|[FullName.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2FFullName.java)|100%|:green_apple:|
|[Credentials.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2FCredentials.java)|100%|:green_apple:|
|[UserId.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2FUserId.java)|100%|:green_apple:|
|[RegisterNewUserImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2Fimpl%2FRegisterNewUserImpl.java)|100%|:green_apple:|
|[JwtServiceIml.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fapplication%2Fin%2Fservices%2Fuser%2Fimpl%2FJwtServiceIml.java)|100%|:green_apple:|
|[GetNewCredentialsUsingRefreshTokenImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fapplication%2Fin%2Fservices%2Fuser%2Fimpl%2FGetNewCredentialsUsingRefreshTokenImpl.java)|100%|:green_apple:|
|[GetNewCredentialsImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fapplication%2Fin%2Fservices%2Fuser%2Fimpl%2FGetNewCredentialsImpl.java)|100%|:green_apple:|
|[ApplicationCredentials.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fapplication%2Fin%2Fservices%2Fuser%2FApplicationCredentials.java)|100%|:green_apple:|
|[TokenRepositoryIml.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fstorage%2FTokenRepositoryIml.java)|100%|:green_apple:|
|[CacheRepositoryIml.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fstorage%2FCacheRepositoryIml.java)|100%|:green_apple:|
|[ImageId.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2FImageId.java)|100%|:green_apple:|
|[ImageExtension.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2FImageExtension.java)|100%|:green_apple:|
|[MetaData.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2FMetaData.java)|100%|:green_apple:|
|[ImageServiceImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fapplication%2Fin%2Fservices%2Fimage%2Fimpl%2FImageServiceImpl.java)|100%|:green_apple:|
|[TryToLoginImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2Fimpl%2FTryToLoginImpl.java)|86.84% **`-13.16%`**|:green_apple:|
|[MinioServiceIml.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fstorage%2FMinioServiceIml.java)|73.27% **`-26.73%`**|:green_apple:|
|[ImageNameWithExtension.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2FImageNameWithExtension.java)|71.08% **`-28.92%`**|:green_apple:|
|[Image.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fimage%2FImage.java)|62.63% **`-37.37%`**|:green_apple:|
|[User.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2FUser.java)|58.66% **`-41.34%`**|:green_apple:|
|[GetPartOfImagesForAuthenticatedUserImpl.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2Fimpl%2FGetPartOfImagesForAuthenticatedUserImpl.java)|50% **`-50%`**|:green_apple:|
|[AuthenticatedUser.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2FAuthenticatedUser.java)|28.91% **`-71.09%`**|:x:|
|[AuthException.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Fdomain%2Fuser%2FAuthException.java)|0%|:x:|
|[FileException.java](https://github.com/asavershin/Images/blob/9828a5adae3d4e2803eff48fb9a0b5170efbdd73/api%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Fasavershin%2Fapi%2Finfrastructure%2Fout%2Fstorage%2FFileException.java)|0%|:x:|

**Pull request merged**
